sonar.projectKey=SubochArtem_CityPulse
sonar.organization=subochartem

sonar.sources=.
sonar.exclusions=**/bin/**,**/obj/**,**/*.spec.ts

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/*.trx
