<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CityPulse.Contracts.Grpc" Version="2.0.0" />
        <PackageReference Include="CityPulse.Contracts.Querying" Version="1.0.0" />
        <PackageReference Include="Mapster" Version="10.0.8" />
        <PackageReference Include="Mapster.DependencyInjection" Version="10.0.8" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    </ItemGroup>

</Project>
