name: SonarCloud Analysis

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    name: Analyze code with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"SubochArtem_CityPulse" \
            /o:"subochartem" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${SONAR_TOKEN}"

      # - name: Restore dependencies
      #   run: dotnet restore

      # - name: Build
      #   run: dotnet build --no-restore --configuration Release

      # - name: Run tests with coverage
      #   run: |
      #     dotnet test --no-build \
      #       --configuration Release \
      #       --logger trx \
      #       --collect:"XPlat Code Coverage" \
      #       -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
